// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bluetooth} from '../models';

export function ScanDevices():Promise<Array<bluetooth.Device>>;
