// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchHeartRate():Promise<number>;

export function ScanDevices():Promise<void>;
