// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchHeartRate() {
  return window['go']['main']['App']['FetchHeartRate']();
}

export function ScanDevices() {
  return window['go']['main']['App']['ScanDevices']();
}
